### ISSUE TITLE
Division of positive intervals

### ISSUE THREAD

**Issue by GoogleCodeExporter** [taschini/pyinterval#1]
```
What steps will reproduce the problem?
1. z = interval[0,1] / interval[0,1]
2. print z

What is the expected output? What do you see instead?

The expected output is z == interval[0, inf], whereas it is computed 
interval[-inf, inf]

What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `l.digasp...@gmail.com` on 29 Jan 2012 at 3:49

**Comment by taschini** [comment]
No, the expected output isindeed `interval[-inf, inf]`, as computed. See equation (4.7.2c) in [1]. 

In short, the reason is that the intervals in question are closed, i.e., they contain their extrema, and in this case they both include 0 — strictly speaking, they are not *positive* intervals. As soon as you have a division between two intervals that both include the origin, the result includes (and therefore equals) the whole extended real line.


[1] Eldon Hansen, G. William Walster, Global Optimization Using Interval Analysis - Second Edition, Revised and Expanded. John Dekker, Inc., 2003.
