### ISSUE TITLE
Too hard and ugly to obtain interval boundaries

### ISSUE THREAD

**Issue by cauebs** [taschini/pyinterval#12]
If you want the extrema, you can use `interval.extrema`, but that returns another `interval`. I can see why, but it's counter-intuitive in some cases. 

Furthermore, `interval.components` returns instances of `interval`, instead of `interval.Component` as I would expect. 

I see no readable way to get the superior and inferior boundaries of an interval, so I've been using `min(interval)[0]` and `max(interval)[0]`, which is a little ugly, but it appears to work. 

Am I missing something? If it's something you agree with, I could try and patch it. I just wanted to discuss it first.

**Comment by taschini** [comment]
There are two ways of iterating over the components of an interval.

You can iterate on the connected components of an interval:

```python
>>> [x for x in interval([1, 2], 3)]
[(1.0, 2.0), (3.0, 3.0)]
```

Each component behaves like a named tuple:

```
>>> x = interval([1, 2], 3)
>>> x[0].inf
1.0
>>> x[1].sup
3.0
```

You can use the [components](http://pyinterval.readthedocs.io/en/latest/api.html#interval.interval.components) attribute to iterate over the components so that each component is itself an interval:

```
>>> [x for x in interval([1, 2], 3).components]
[interval([1.0, 2.0]), interval([3.0])]
```

I updated the documentation to explain this difference.  I hope it is clear now.

**Comment by cauebs** [comment]
Okay, I understand. Thank you for your work, it's been useful to me :)
